version: '3.8'
services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto_secure
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./certs/broker:/mosquitto/certs:ro
      - ./certs/ca:/mosquitto/ca:ro
    restart: unless-stopped
